<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Leds.Player.Application\Leds.Player.Application.csproj" />
    <ProjectReference Include="..\Leds.Player.Domain\Leds.Player.Domain.csproj" />
  </ItemGroup>

</Project>
