services:
  game-engine-postgres:
    image: postgres:16
    container_name: leds-game-engine-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: leds_game_engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - game_engine_postgres_data:/var/lib/postgresql/data

  player-postgres:
    image: postgres:16
    container_name: leds-player-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: leds_player
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - player_postgres_data:/var/lib/postgresql/data

  catalog-postgres:
    image: postgres:16
    container_name: leds-catalog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: leds_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data

volumes:
  game_engine_postgres_data:
  player_postgres_data:
  catalog_postgres_data:
