// <auto-generated />
using System;
using Leds.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Leds.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Leds.Catalog.Infrastructure.Persistence.Entities.CatalogSeedVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<string>("Checksum")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("checksum");

                    b.Property<string>("SeedKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("seed_key");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SeedKey", "Version")
                        .IsUnique();

                    b.ToTable("catalog_seed_versions", (string)null);
                });

            modelBuilder.Entity("Leds.Catalog.Infrastructure.Persistence.Entities.CatalogTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("TagKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tag_key");

                    b.HasKey("Id");

                    b.HasIndex("TagKey")
                        .IsUnique();

                    b.ToTable("catalog_tags", (string)null);
                });

            modelBuilder.Entity("Leds.Catalog.Infrastructure.Persistence.Entities.CurseDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseWeight")
                        .HasColumnType("integer")
                        .HasColumnName("base_weight");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("duration");

                    b.Property<Guid?>("EffectSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("effect_set_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("key");

                    b.Property<int?>("MaxDepth")
                        .HasColumnType("integer")
                        .HasColumnName("max_depth");

                    b.Property<int?>("MinDepth")
                        .HasColumnType("integer")
                        .HasColumnName("min_depth");

                    b.Property<string>("NarrativeText")
                        .HasColumnType("text")
                        .HasColumnName("narrative_text");

                    b.Property<string>("SelectionGroup")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("selection_group");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trigger");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EffectSetId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("catalog_curse_definitions", (string)null);
                });

            modelBuilder.Entity("Leds.Catalog.Infrastructure.Persistence.Entities.CurseTagEntity", b =>
                {
                    b.Property<Guid>("CurseDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("curse_definition_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("CurseDefinitionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("catalog_curse_tags", (string)null);
                });

            modelBuilder.Entity("Leds.Catalog.Infrastructure.Persistence.Entities.EffectDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BehaviorTag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("behavior_tag");

                    b.Property<string>("Condition")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("condition");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("duration");

                    b.Property<Guid>("EffectSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("effect_set_id");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("effect_type");

                    b.Property<string>("GenerationTag")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("generation_tag");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("SelectionGroup")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("selection_group");

                    b.Property<string>("StackPolicy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stack_policy");

                    b.Property<string>("TargetScope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_scope");

                    b.Property<decimal?>("Value")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("value");

                    b.Property<string>("ValueMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("value_mode");

                    b.HasKey("Id");

                    b.HasIndex("EffectSetId", "Order");

                    b.ToTable("catalog_effect_definitions", (string)null);
                });

            modelBuilder.Entity("Leds.Catalog.Infrastructure.Persistence.Entities.EffectSetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("catalog_effect_sets", (string)null);
                });

            modelBuilder.Entity("Leds.Catalog.Infrastructure.Persistence.Entities.EnemyDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("archetype");

                    b.Property<int>("BaseDifficulty")
                        .HasColumnType("integer")
                        .HasColumnName("base_difficulty");

                    b.Property<int>("BaseWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("base_weight");

                    b.Property<string>("BoundRoomKeysJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("bound_room_keys_json");

                    b.Property<string>("CompatibleRoomTypesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("compatible_room_types_json")
                        .HasComment("Legacy JSON compatibility column. Structured room pools/tags are relational in data-model-0.1.");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<int>("EncounterWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("encounter_weight");

                    b.Property<string>("Family")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("family");

                    b.Property<bool>("IsBoss")
                        .HasColumnType("boolean")
                        .HasColumnName("is_boss");

                    b.Property<bool>("IsElite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_elite");

                    b.Property<string>("Key")
                        .IsRequi