// <auto-generated />
using System;
using Leds.GameEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Leds.GameEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameEngineDbContext))]
    [Migration("20260616142243_IntroduceDeterministicSelectionContext")]
    partial class IntroduceDeterministicSelectionContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.ActiveCurseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<string>("CurseDefinitionKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("curse_definition_key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<double>("DifficultyDelta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("difficulty_delta");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("NextCombatOnly")
                        .HasColumnName("duration");

                    b.Property<string>("EffectSetKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("effect_set_key");

                    b.Property<Guid?>("ExpiresAtRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("expires_at_room_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<Guid?>("RunEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("Severity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("CurseDefinitionKey")
                        .HasDatabaseName("IX_run_active_curses_curse_definition_key");

                    b.HasIndex("RunEntityId");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_run_active_curses_run_id");

                    b.ToTable("run_active_curses", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatActionRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorSide")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_side");

                    b.Property<Guid>("CombatId")
                        .HasColumnType("uuid")
                        .HasColumnName("combat_id");

                    b.Property<int>("DamageDealt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("damage_dealt");

                    b.Property<int>("DamageTaken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("damage_taken");

                    b.Property<string>("EffectsApplied")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("effects_applied");

                    b.Property<int>("GuardAbsorbed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("guard_absorbed");

                    b.Property<int>("GuardDamage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("guard_damage");

                    b.Property<int>("GuardGained")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("guard_gained");

                    b.Property<int>("HealingDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("healing_done");

                    b.Property<int>("HealingReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("healing_received");

                    b.Property<int>("MitigatedDamage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mitigated_damage");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<int>("RawDamage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("raw_damage");

                    b.Property<string>("SkillDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("skill_display_name");

                    b.Property<string>("SkillKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("skill_key");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<string>("TargetIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("target_ids");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.Property<int>("VitalityDamage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vitality_damage");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("CombatId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("TurnNumber");

                    b.ToTable("run_combat_actions", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveCombatantId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_combatant_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("Status");

                    b.ToTable("run_active_combats", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantBaseStatSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AtbReadyThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("atb_ready_threshold");

                    b.Property<int>("AttackPower")
                        .HasColumnType("integer")
                        .HasColumnName("attack_power");

                    b.Property<int>("Charge")
                        .HasColumnType("integer")
                        .HasColumnName("charge");

                    b.Property<Guid>("CombatantId")
                        .HasColumnType("uuid")
                        .HasColumnName("combatant_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<int>("Focus")
                        .HasColumnType("integer")
                        .HasColumnName("focus");

                    b.Property<int>("Initiative")
                        .HasColumnType("integer")
                        .HasColumnName("initiative");

                    b.Property<int>("Mana")
                        .HasColumnType("integer")
                        .HasColumnName("mana");

                    b.Property<int>("MaxVitality")
                        .HasColumnType("integer")
                        .HasColumnName("max_vitality");

                    b.Property<int>("Recovery")
                        .HasColumnType("integer")
                        .HasColumnName("recovery");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<int>("StartingGuard")
                        .HasColumnType("integer")
                        .HasColumnName("starting_guard");

                    b.HasKey("Id");

                    b.HasIndex("CombatantId")
                        .IsUnique();

                    b.ToTable("run_combatant_base_stat_snapshots", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("archetype");

                    b.Property<int>("BaseGuard")
                        .HasColumnType("integer")
                        .HasColumnName("base_guard");

                    b.Property<int>("Charge")
                        .HasColumnType("integer")
                        .HasColumnName("charge");

                    b.Property<Guid>("CombatId")
                        .HasColumnType("uuid")
                        .HasColumnName("combat_id");

                    b.Property<int>("CurrentVitality")
                        .HasColumnType("integer")
                        .HasColumnName("current_vitality");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<int>("Guard")
                        .HasColumnType("integer")
                        .HasColumnName("guard");

                    b.Property<int>("Mana")
                        .HasColumnType("integer")
                        .HasColumnName("mana");

                    b.Property<int>("MaxVitality")
                        .HasColumnType("integer")
                        .HasColumnName("max_vitality");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("side");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CombatId");

                    b.HasIndex("Side");

                    b.HasIndex("Status");

                    b.ToTable("run_combatants", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantRuntimeStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActionRecoveryUntilTick")
                        .HasColumnType("integer")
                        .HasColumnName("action_recovery_until_tick");

                    b.Property<int?>("AtbGaugeValue")
                        .HasColumnType("integer")
                        .HasColumnName("atb_gauge_value");

                    b.Property<Guid>("CombatantId")
                        .HasColumnType("uuid")
                        .HasColumnName("combatant_id");

                    b.Property<int>("CurrentCharge")
                        .HasColumnType("integer")
                        .HasColumnName("current_charge");

                    b.Property<int>("CurrentFocus")
                        .HasColumnType("integer")
                        .HasColumnName("current_focus");

                    b.Property<int>("CurrentGuard")
                        .HasColumnType("integer")
                        .HasColumnName("current_guard");

                    b.Property<int>("CurrentMana")
                        .HasColumnType("integer")
                        .HasColumnName("current_mana");

                    b.Property<int>("CurrentVitality")
                        .HasColumnType("integer")
                        .HasColumnName("current_vitality");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CombatantId")
                        .IsUnique();

                    b.ToTable("run_combatant_runtime_states", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantSkillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BasePower")
                        .HasColumnType("integer")
                        .HasColumnName("base_power");

                    b.Property<int>("ChargeCost")
                        .HasColumnType("integer")
                        .HasColumnName("charge_cost");

                    b.Property<Guid>("CombatantId")
                        .HasColumnType("uuid")
                        .HasColumnName("combatant_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("effect_type");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<int>("ManaCost")
                        .HasColumnType("integer")
                        .HasColumnName("mana_cost");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("skill_type");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("TargetingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("targeting_type");

                    b.HasKey("Id");

                    b.HasIndex("CombatantId");

                    b.HasIndex("Key");

                    b.ToTable("run_combatant_skills", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChosenEventOptionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("chosen_event_option_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsBoss")
                        .HasColumnType("boolean")
                        .HasColumnName("is_boss");

                    b.Property<int>("Lane")
                        .HasColumnType("integer")
                        .HasColumnName("lane");

                    b.Property<string>("RewardProfile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reward_profile");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer")
                        .HasColumnName("risk_level");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("Row");

                    b.HasIndex("State");

                    b.ToTable("run_nodes", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeParentNodeEntity", b =>
                {
                    b.Property<Guid>("MapNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_node_id");

                    b.Property<Guid>("ParentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_node_id");

                    b.HasKey("MapNodeId", "ParentNodeId");

                    b.HasIndex("MapNodeId");

                    b.HasIndex("ParentNodeId");

                    b.ToTable("run_node_parent_nodes", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Destination")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("destination");

                    b.Property<string>("EventVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("ProcessedAtUtc");

                    b.HasIndex("Type");

                    b.ToTable("game_engine_outbox_messages", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.PlayerRuntimeSkillEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<int>("BasePower")
                        .HasColumnType("integer")
                        .HasColumnName("base_power");

                    b.Property<int>("ChargeCost")
                        .HasColumnType("integer")
                        .HasColumnName("charge_cost");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("effect_type");

                    b.Property<int>("ManaCost")
                        .HasColumnType("integer")
                        .HasColumnName("mana_cost");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("skill_type");

                    b.Property<string>("TargetingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("targeting_type");

                    b.HasKey("RunId", "Key");

                    b.ToTable("run_player_skills", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.PlayerRuntimeStateEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("Charge")
                        .HasColumnType("integer")
                        .HasColumnName("charge");

                    b.Property<int>("CurrentVitality")
                        .HasColumnType("integer")
                        .HasColumnName("current_vitality");

                    b.Property<int>("Guard")
                        .HasColumnType("integer")
                        .HasColumnName("guard");

                    b.Property<int>("Mana")
                        .HasColumnType("integer")
                        .HasColumnName("mana");

                    b.Property<int>("MaxVitality")
                        .HasColumnType("integer")
                        .HasColumnName("max_vitality");

                    b.HasKey("RunId");

                    b.ToTable("run_player_states", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RewardOfferEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CatalogRewardTemplateKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("catalog_reward_template_key");

                    b.Property<string>("CatalogRewardTemplateVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("catalog_reward_template_version");

                    b.Property<string>("CombatTier")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("combat_tier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal?>("DifficultyMultiplier")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("difficulty_multiplier");

                    b.Property<decimal?>("RewardPowerMultiplier")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("reward_power_multiplier");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTime?>("SelectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selected_at_utc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("State");

                    b.ToTable("run_reward_offers", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RewardOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("BaseAmount")
                        .HasColumnType("integer")
                        .HasColumnName("base_amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EffectSetKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("effect_set_key");

                    b.Property<string>("EffectSetVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("effect_set_version");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_selected");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("label");

                    b.Property<string>("PayloadKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("payload_key");

                    b.Property<string>("PayloadType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_type");

                    b.Property<Guid>("RewardOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_offer_id");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reward_type");

                    b.Property<int?>("ScaledAmount")
                        .HasColumnType("integer")
                        .HasColumnName("scaled_amount");

                    b.Property<int>("SelectionOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("selection_order");

                    b.HasKey("Id");

                    b.HasIndex("RewardOfferId");

                    b.ToTable("run_reward_options", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BossDangerHint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("boss_danger_hint");

                    b.Property<string>("BossEnemyTemplateKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("boss_enemy_template_key");

                    b.Property<string>("BossId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("boss_id");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("boss_name");

                    b.Property<string>("BossRoomType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("boss_room_type");

                    b.Property<int>("CurrentNodeDepth")
                        .HasColumnType("integer")
                        .HasColumnName("current_node_depth");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("LayoutTemplateKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("layout_template_key");

                    b.Property<string>("LayoutTemplateVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("layout_template_version");

                    b.Property<int>("MaxNodeDepth")
                        .HasColumnType("integer")
                        .HasColumnName("max_node_depth");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("room_type");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("state");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("theme");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("State");

                    b.ToTable("run_rooms", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunActivePalaceLawEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Domains")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("domains");

                    b.Property<string>("Duration")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("duration");

                    b.Property<Guid?>("ExpiresAtRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("expires_at_room_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<Guid>("LawId")
                        .HasColumnType("uuid")
                        .HasColumnName("law_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .HasDatabaseName("IX_run_active_palace_laws_key");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_run_active_palace_laws_run_id");

                    b.ToTable("run_active_palace_laws", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunCharacterSkillSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BasePower")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("base_power");

                    b.Property<Guid>("CharacterSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_snapshot_id");

                    b.Property<int>("ChargeCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("charge_cost");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("effect_type");

                    b.Property<int>("ManaCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mana_cost");

                    b.Property<string>("SkillDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("skill_definition_key");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("skill_type");

                    b.Property<string>("TargetingMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("targeting_mode");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSnapshotId");

                    b.HasIndex("SkillDefinitionKey");

                    b.ToTable("run_character_skill_snapshots", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunCharacterSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("definition_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("PlayerSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_snapshot_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerSnapshotId");

                    b.ToTable("run_character_snapshots", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunCharacterStatSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttackPower")
                        .HasColumnType("integer")
                        .HasColumnName("attack_power");

                    b.Property<Guid>("CharacterSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_snapshot_id");

                    b.Property<int>("Charge")
                        .HasColumnType("integer")
                        .HasColumnName("charge");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<int>("Focus")
                        .HasColumnType("integer")
                        .HasColumnName("focus");

                    b.Property<int>("Initiative")
                        .HasColumnType("integer")
                        .HasColumnName("initiative");

                    b.Property<int>("Mana")
                        .HasColumnType("integer")
                        .HasColumnName("mana");

                    b.Property<int>("MaxVitality")
                        .HasColumnType("integer")
                        .HasColumnName("max_vitality");

                    b.Property<int>("Recovery")
                        .HasColumnType("integer")
                        .HasColumnName("recovery");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<int>("StartingGuard")
                        .HasColumnType("integer")
                        .HasColumnName("starting_guard");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSnapshotId")
                        .IsUnique();

                    b.ToTable("run_character_stat_snapshots", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveCombatId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_combat_id");

                    b.Property<int>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("attack");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("current_hp");

                    b.Property<Guid>("CurrentRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_room_id");

                    b.Property<int>("CurrentRoomIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_room_index");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("GeneratorVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("generator_version");

                    b.Property<string>("MarkovMatrixVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("markov_matrix_version");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<Guid?>("PendingRewardOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_reward_offer_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("PreSuspendStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pre_suspend_status");

                    b.Property<DateTime?>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at_utc");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("seed");

                    b.Property<string>("SnapshotActivePalaceLaws")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_active_palace_laws");

                    b.Property<int?>("SnapshotAttack")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_attack");

                    b.Property<int?>("SnapshotCurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_current_hp");

                    b.Property<int?>("SnapshotDefense")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_defense");

                    b.Property<string>("SnapshotMemoryFragments")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_memory_fragments");

                    b.Property<int?>("SnapshotSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_speed");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCombatId")
                        .IsUnique();

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Status");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("definition_key");

                    b.Property<string>("DefinitionVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("definition_version");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<int>("EffectAmount")
                        .HasColumnType("integer")
                        .HasColumnName("effect_amount");

                    b.Property<string>("EffectSetKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("effect_set_key");

                    b.Property<string>("EffectSummary")
                        .HasColumnType("text")
                        .HasColumnName("effect_summary");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("effect_type");

                    b.Property<bool?>("IsUsableInCombat")
                        .HasColumnType("boolean")
                        .HasColumnName("is_usable_in_combat");

                    b.Property<bool?>("IsUsableOutsideCombat")
                        .HasColumnType("boolean")
                        .HasColumnName("is_usable_outside_combat");

                    b.Property<string>("Lifecycle")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lifecycle");

                    b.Property<int?>("MaxStack")
                        .HasColumnType("integer")
                        .HasColumnName("max_stack");

                    b.Property<string>("NarrativeText")
                        .HasColumnType("text")
                        .HasColumnName("narrative_text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rarity");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid?>("SourceRewardOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_reward_option_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<string>("UsageMode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("usage_mode");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionKey");

                    b.HasIndex("RunId");

                    b.HasIndex("SourceRewardOptionId");

                    b.ToTable("run_items", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunMemoryFragmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FragmentKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fragment_key");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("run_memory_fragments", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunModifierEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("duration");

                    b.Property<Guid?>("ExpiresAtCombatId")
                        .HasColumnType("uuid")
                        .HasColumnName("expires_at_combat_id");

                    b.Property<Guid?>("ExpiresAtRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("expires_at_room_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<string>("StackPolicy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Additive")
                        .HasColumnName("stack_policy");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.Property<string>("ValueMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Flat")
                        .HasColumnName("value_mode");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("run_modifiers", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunPlayerSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("run_player_snapshots", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.SelectionDecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("algorithm_version");

                    b.Property<string>("ContextKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("context_key");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decision_type");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("seed");

                    b.Property<string>("SelectedKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("selected_key");

                    b.Property<string>("SelectionGroup")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("selection_group");

                    b.HasKey("Id");

                    b.HasIndex("DecisionType")
                        .HasDatabaseName("IX_run_selection_decisions_decision_type");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_run_selection_decisions_run_id");

                    b.HasIndex("SelectedKey")
                        .HasDatabaseName("IX_run_selection_decisions_selected_key");

                    b.ToTable("run_selection_decisions", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.ActiveCurseEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", null)
                        .WithMany("ActiveCurses")
                        .HasForeignKey("RunEntityId");

                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatActionRecordEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatEntity", "Combat")
                        .WithMany()
                        .HasForeignKey("CombatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combat");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantBaseStatSnapshotEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantEntity", "Combatant")
                        .WithOne("BaseStatSnapshot")
                        .HasForeignKey("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantBaseStatSnapshotEntity", "CombatantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combatant");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatEntity", "Combat")
                        .WithMany("Combatants")
                        .HasForeignKey("CombatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combat");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantRuntimeStateEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantEntity", "Combatant")
                        .WithOne("RuntimeState")
                        .HasForeignKey("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantRuntimeStateEntity", "CombatantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combatant");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantSkillEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantEntity", "Combatant")
                        .WithMany("Skills")
                        .HasForeignKey("CombatantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combatant");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RoomEntity", "Room")
                        .WithMany("Nodes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeParentNodeEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeEntity", "MapNode")
                        .WithMany("ParentNodeLinks")
                        .HasForeignKey("MapNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapNode");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.PlayerRuntimeSkillEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.PlayerRuntimeStateEntity", "PlayerState")
                        .WithMany("Skills")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerState");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.PlayerRuntimeStateEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithOne("PlayerState")
                        .HasForeignKey("Leds.GameEngine.Infrastructure.Persistence.Entities.PlayerRuntimeStateEntity", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RewardOfferEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RewardOptionEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RewardOfferEntity", "RewardOffer")
                        .WithMany("Options")
                        .HasForeignKey("RewardOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewardOffer");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RoomEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithMany("Rooms")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunActivePalaceLawEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithMany("ActivePalaceLaws")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunCharacterSkillSnapshotEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunCharacterSnapshotEntity", "CharacterSnapshot")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSnapshot");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunCharacterSnapshotEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunPlayerSnapshotEntity", "PlayerSnapshot")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerSnapshot");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunCharacterStatSnapshotEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunCharacterSnapshotEntity", "CharacterSnapshot")
                        .WithOne("StatBlock")
                        .HasForeignKey("Leds.GameEngine.Infrastructure.Persistence.Entities.RunCharacterStatSnapshotEntity", "CharacterSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSnapshot");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatEntity", "ActiveCombat")
                        .WithOne("Run")
                        .HasForeignKey("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "ActiveCombatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveCombat");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunItemEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithMany("InventoryItems")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunMemoryFragmentEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithMany("MemoryFragments")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunModifierEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithMany("RunModifiers")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunPlayerSnapshotEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithOne("PlayerSnapshot")
                        .HasForeignKey("Leds.GameEngine.Infrastructure.Persistence.Entities.RunPlayerSnapshotEntity", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.SelectionDecisionEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatEntity", b =>
                {
                    b.Navigation("Combatants");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatantEntity", b =>
                {
                    b.Navigation("BaseStatSnapshot");

                    b.Navigation("RuntimeState");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeEntity", b =>
                {
                    b.Navigation("ParentNodeLinks");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.PlayerRuntimeStateEntity", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RewardOfferEntity", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RoomEntity", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunCharacterSnapshotEntity", b =>
                {
                    b.Navigation("Skills");

                    b.Navigation("StatBlock");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", b =>
                {
                    b.Navigation("ActiveCurses");

                    b.Navigation("ActivePalaceLaws");

                    b.Navigation("InventoryItems");

                    b.Navigation("MemoryFragments");

                    b.Navigation("PlayerSnapshot");

                    b.Navigation("PlayerState");

                    b.Navigation("Rooms");

                    b.Navigation("RunModifiers");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunPlayerSnapshotEntity", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
