// <auto-generated />
using System;
using Leds.GameEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Leds.GameEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameEngineDbContext))]
    [Migration("20260610114908_AddRunMapStatePersistence")]
    partial class AddRunMapStatePersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChosenEventOptionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("chosen_event_option_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsBoss")
                        .HasColumnType("boolean")
                        .HasColumnName("is_boss");

                    b.Property<int>("Lane")
                        .HasColumnType("integer")
                        .HasColumnName("lane");

                    b.Property<string>("RewardProfile")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reward_profile");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer")
                        .HasColumnName("risk_level");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("Row");

                    b.HasIndex("State");

                    b.ToTable("run_nodes", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeParentNodeEntity", b =>
                {
                    b.Property<Guid>("MapNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_node_id");

                    b.Property<Guid>("ParentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_node_id");

                    b.HasKey("MapNodeId", "ParentNodeId");

                    b.HasIndex("MapNodeId");

                    b.HasIndex("ParentNodeId");

                    b.ToTable("run_node_parent_nodes", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BossDangerHint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("boss_danger_hint");

                    b.Property<string>("BossEnemyTemplateKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("boss_enemy_template_key");

                    b.Property<string>("BossId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("boss_id");

                    b.Property<string>("BossName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("boss_name");

                    b.Property<string>("BossRoomType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("boss_room_type");

                    b.Property<int>("CurrentNodeDepth")
                        .HasColumnType("integer")
                        .HasColumnName("current_node_depth");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<string>("LayoutTemplateKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("layout_template_key");

                    b.Property<string>("LayoutTemplateVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("layout_template_version");

                    b.Property<int>("MaxNodeDepth")
                        .HasColumnType("integer")
                        .HasColumnName("max_node_depth");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("room_type");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("state");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("theme");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("State");

                    b.ToTable("run_rooms", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunActivePalaceLawEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Domains")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("domains");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<Guid>("LawId")
                        .HasColumnType("uuid")
                        .HasColumnName("law_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("run_active_palace_laws", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveCombatId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_combat_id");

                    b.Property<int>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("attack");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("current_hp");

                    b.Property<Guid>("CurrentRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_room_id");

                    b.Property<int>("CurrentRoomIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_room_index");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("GeneratorVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("generator_version");

                    b.Property<string>("MarkovMatrixVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("markov_matrix_version");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<Guid?>("PendingRewardOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("pending_reward_offer_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("PreSuspendStatus")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pre_suspend_status");

                    b.Property<DateTime?>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at_utc");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("seed");

                    b.Property<string>("SnapshotActivePalaceLaws")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_active_palace_laws");

                    b.Property<int?>("SnapshotAttack")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_attack");

                    b.Property<int?>("SnapshotCurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_current_hp");

                    b.Property<int?>("SnapshotDefense")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_defense");

                    b.Property<string>("SnapshotMemoryFragments")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_memory_fragments");

                    b.Property<int?>("SnapshotSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_speed");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Status");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunMemoryFragmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FragmentKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fragment_key");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("run_memory_fragments", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RoomEntity", "Room")
                        .WithMany("Nodes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeParentNodeEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeEntity", "MapNode")
                        .WithMany("ParentNodeLinks")
                        .HasForeignKey("MapNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapNode");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RoomEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithMany("Rooms")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunActivePalaceLawEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithMany("ActivePalaceLaws")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunMemoryFragmentEntity", b =>
                {
                    b.HasOne("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", "Run")
                        .WithMany("MemoryFragments")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.MapNodeEntity", b =>
                {
                    b.Navigation("ParentNodeLinks");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RoomEntity", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.RunEntity", b =>
                {
                    b.Navigation("ActivePalaceLaws");

                    b.Navigation("MemoryFragments");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
