// <auto-generated />
using System;
using Leds.Player.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Leds.Player.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    [Migration("20260801075430_AddHimLitShardCount")]
    partial class AddHimLitShardCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseCharge")
                        .HasColumnType("integer")
                        .HasColumnName("base_charge")
                        .HasComment("Legacy compatibility column. Use player_character_stat_blocks.charge for data-model-0.1.");

                    b.Property<int>("BaseMana")
                        .HasColumnType("integer")
                        .HasColumnName("base_mana")
                        .HasComment("Legacy compatibility column. Use player_character_stat_blocks.mana for data-model-0.1.");

                    b.Property<string>("CharacterType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Standard")
                        .HasColumnName("character_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("definition_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<int>("MaxVitality")
                        .HasColumnType("integer")
                        .HasColumnName("max_vitality")
                        .HasComment("Legacy compatibility column. Use player_character_stat_blocks.max_vitality for data-model-0.1.");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<string>("SkillKeysJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_keys_json")
                        .HasComment("Legacy compatibility column. Use player_character_skills for data-model-0.1.");

                    b.Property<int>("StatPointsInvested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stat_points_invested");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.HasIndex("PlayerProfileId", "DefinitionKey")
                        .IsUnique();

                    b.ToTable("player_characters", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at_utc");

                    b.Property<string>("EquipmentSlot")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("Relic")
                        .HasColumnName("equipment_slot");

                    b.Property<bool>("IsEquipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_equipped");

                    b.Property<string>("ItemDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("item_definition_key");

                    b.Property<Guid>("PlayerCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_character_id");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacterId", "ItemDefinitionKey")
                        .IsUnique();

                    b.ToTable("player_character_items", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterSkillEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EquipmentSlot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEquipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_equipped");

                    b.Property<Guid>("PlayerCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_character_id");

                    b.Property<string>("SkillDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("skill_definition_key");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UnlockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacterId", "SkillDefinitionKey")
                        .IsUnique();

                    b.ToTable("player_character_skills", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterStatBlockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttackPower")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12)
                        .HasColumnName("attack_power");

                    b.Property<int>("Charge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("charge");

                    b.Property<int>("Defense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6)
                        .HasColumnName("defense");

                    b.Property<int>("Focus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("focus");

                    b.Property<int>("Initiative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("initiative");

                    b.Property<int>("MagicAttack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("magic_attack");

                    b.Property<int>("MagicDefense")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("magic_defense");

                    b.Property<int>("Mana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mana");

                    b.Property<int>("MaxVitality")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("max_vitality");

                    b.Property<int>("Movement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("movement");

                    b.Property<Guid>("PlayerCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_character_id");

                    b.Property<int>("Speed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("speed");

                    b.Property<int>("StartingGuard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("starting_guard");

                    b.HasKey("Id");

                    b.HasIndex("PlayerCharacterId")
                        .IsUnique();

                    b.ToTable("player_character_stat_blocks", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerNpcReputationScoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CurrentDialogueNodeKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("current_dialogue_node_key");

                    b.Property<string>("NpcKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("npc_key");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("score");

                    b.Property<int>("TimesMet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("times_met");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId", "NpcKey")
                        .IsUnique();

                    b.ToTable("player_npc_reputation_scores", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerPermanentItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at_utc");

                    b.Property<string>("ContainedLiquidDefinitionKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contained_liquid_definition_key");

                    b.Property<string>("ItemDefinitionKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("item_definition_key");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<Guid?>("SourceRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_run_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId", "ItemDefinitionKey")
                        .IsUnique();

                    b.ToTable("player_permanent_items", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerPermanentUnlockEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<Guid?>("SourceRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_run_id");

                    b.Property<string>("UnlockKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("unlock_key");

                    b.Property<string>("UnlockType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("unlock_type");

                    b.Property<DateTimeOffset>("UnlockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId", "UnlockKey")
                        .IsUnique();

                    b.ToTable("player_permanent_unlocks", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthSubjectId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("auth_subject_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<int>("HimLitShardCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("him_lit_shard_count");

                    b.Property<int>("PalaceShardCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("palace_shard_count");

                    b.Property<int>("TotalRunsAbandoned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_runs_abandoned");

                    b.Property<int>("TotalRunsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_runs_completed");

                    b.Property<int>("TotalRunsFailed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_runs_failed");

                    b.Property<int>("TotalRunsStarted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_runs_started");

                    b.Property<int>("TotalStatPointsEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_stat_points_earned");

                    b.Property<int>("UnspentStatPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("unspent_stat_points");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AuthSubjectId");

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerRunStatisticEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CombatsLost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("combats_lost");

                    b.Property<int>("CombatsWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("combats_won");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<int>("FinalDepth")
                        .HasColumnType("integer")
                        .HasColumnName("final_depth");

                    b.Property<string>("GeneratorVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("generator_version");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<int>("RewardsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rewards_selected");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Seed")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("seed");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("TotalDamageDealt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_damage_dealt");

                    b.Property<int>("TotalDamageTaken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_damage_taken");

                    b.Property<int>("TotalGuardAbsorbed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_guard_absorbed");

                    b.Property<int>("TotalHealingDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_healing_done");

                    b.Property<int>("TotalItemsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_items_used");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("player_run_statistics", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.ProcessedIntegrationEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("EventId");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("player_processed_integration_events", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterEntity", b =>
                {
                    b.HasOne("Leds.Player.Infrastructure.Persistence.Entities.PlayerProfileEntity", "PlayerProfile")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterItemEntity", b =>
                {
                    b.HasOne("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterEntity", "PlayerCharacter")
                        .WithMany("Items")
                        .HasForeignKey("PlayerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerCharacter");
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterSkillEntity", b =>
                {
                    b.HasOne("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterEntity", "PlayerCharacter")
                        .WithMany("Skills")
                        .HasForeignKey("PlayerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerCharacter");
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterStatBlockEntity", b =>
                {
                    b.HasOne("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterEntity", "PlayerCharacter")
                        .WithOne("StatBlock")
                        .HasForeignKey("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterStatBlockEntity", "PlayerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerCharacter");
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerNpcReputationScoreEntity", b =>
                {
                    b.HasOne("Leds.Player.Infrastructure.Persistence.Entities.PlayerProfileEntity", "PlayerProfile")
                        .WithMany("NpcReputationScores")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerPermanentItemEntity", b =>
                {
                    b.HasOne("Leds.Player.Infrastructure.Persistence.Entities.PlayerProfileEntity", "PlayerProfile")
                        .WithMany("PermanentItems")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerPermanentUnlockEntity", b =>
                {
                    b.HasOne("Leds.Player.Infrastructure.Persistence.Entities.PlayerProfileEntity", "PlayerProfile")
                        .WithMany("PermanentUnlocks")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerRunStatisticEntity", b =>
                {
                    b.HasOne("Leds.Player.Infrastructure.Persistence.Entities.PlayerProfileEntity", "PlayerProfile")
                        .WithMany("RunStatistics")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Skills");

                    b.Navigation("StatBlock");
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerProfileEntity", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("NpcReputationScores");

                    b.Navigation("PermanentItems");

                    b.Navigation("PermanentUnlocks");

                    b.Navigation("RunStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
