// <auto-generated />
using System;
using Leds.Player.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Leds.Player.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    partial class PlayerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseCharge")
                        .HasColumnType("integer")
                        .HasColumnName("base_charge");

                    b.Property<int>("BaseMana")
                        .HasColumnType("integer")
                        .HasColumnName("base_mana");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefinitionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("definition_key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<int>("MaxVitality")
                        .HasColumnType("integer")
                        .HasColumnName("max_vitality");

                    b.Property<Guid>("PlayerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_profile_id");

                    b.Property<string>("SkillKeysJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill_keys_json");

                    b.HasKey("Id");

                    b.HasIndex("PlayerProfileId");

                    b.ToTable("player_characters", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<int>("TotalRunsAbandoned")
                        .HasColumnType("integer")
                        .HasColumnName("total_runs_abandoned");

                    b.Property<int>("TotalRunsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("total_runs_completed");

                    b.Property<int>("TotalRunsFailed")
                        .HasColumnType("integer")
                        .HasColumnName("total_runs_failed");

                    b.Property<int>("TotalRunsStarted")
                        .HasColumnType("integer")
                        .HasColumnName("total_runs_started");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.ProcessedIntegrationEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("EventId");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("player_processed_integration_events", (string)null);
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerCharacterEntity", b =>
                {
                    b.HasOne("Leds.Player.Infrastructure.Persistence.Entities.PlayerProfileEntity", "PlayerProfile")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("Leds.Player.Infrastructure.Persistence.Entities.PlayerProfileEntity", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
