namespace Leds.Catalog.Infrastructure.Persistence;

internal sealed record CanonicalTacticalSkillContract(
    int Range, string AreaShape, bool RequiresLineOfSight);

internal static class CanonicalTacticalSkillContracts
{
    private static readonly IReadOnlyDictionary<string, CanonicalTacticalSkillContract> ByKey =
        new Dictionary<string, CanonicalTacticalSkillContract>(StringComparer.Ordinal)
        {
            ["skill.basic.strike"] = new(1, "Single", false),
            ["canon.skill.flamme-froide"] = new(3, "Cross", true),
            ["canon.skill.priere-aspiration"] = new(4, "Single", true),
            ["canon.skill.transmutation"] = new(0, "Single", false),
            ["canon.skill.brume"] = new(3, "Diamond", true),
            ["canon.skill.flamme-seraphine"] = new(4, "Single", true),
            ["canon.skill.se-taire"] = new(3, "Diamond", true),
            ["canon.skill.construction-perpetuelle"] = new(0, "Single", false),
            ["canon.skill.liberte-retrouvee"] = new(1, "Single", false),
            ["canon.skill.connaissance-academique"] = new(3, "Diamond", true),
            ["canon.skill.regard-infantile"] = new(4, "Single", true),
            ["canon.skill.frayeur-organique"] = new(4, "Single", true),
            ["canon.skill.clairvoyance"] = new(3, "Diamond", true),
            ["canon.skill.impulsivite"] = new(1, "Single", false),
            ["canon.skill.favorite-de-elise"] = new(0, "Single", false),
            ["canon.skill.creation"] = new(4, "Single", true),
            ["canon.skill.ecriture-continuelle"] = new(4, "Single", true),
            ["canon.skill.larme-des-enfers"] = new(4, "Single", true),
            ["canon.skill.souffle-de-la-forge"] = new(4, "Single", true),
            ["canon.skill.contemplation-infinie"] = new(4, "Single", true),
            ["canon.skill.silence"] = new(4, "Single", true),
            ["canon.skill.sursaut-memoriel"] = new(4, "Single", true),
            ["canon.skill.larme-elise"] = new(4, "Single", true),
            ["canon.skill.caresse-de-mane"] = new(0, "Single", false),
            ["canon.skill.anagramme"] = new(4, "Single", true),
            ["canon.skill.lecture-des-silences"] = new(4, "Single", true),
            ["canon.skill.nevrose"] = new(4, "Single", true),
            ["canon.skill.plongee-dans-la-folie"] = new(4, "Single", true),
            ["canon.skill.egide"] = new(0, "Single", false),
            ["canon.skill.rempart"] = new(2, "Cross", true),
            ["canon.skill.symphonie-des-enfers"] = new(3, "Diamond", true),
            ["canon.skill.deluge-du-styx"] = new(3, "Diamond", true),
            ["canon.skill.destinee-cruelle"] = new(0, "Single", false),
            ["canon.skill.fondations-de-thomas"] = new(1, "Single", false),
            ["canon.skill.veillee-de-mina"] = new(3, "Single", true),
            ["canon.skill.baiser-delise"] = new(3, "Single", true),
            ["canon.skill.vol-a-la-tire"] = new(1, "Single", false),
            ["canon.skill.pli-du-tapis"] = new(1, "Single", false),
            ["canon.skill.etouffement-feutre"] = new(4, "Single", true),
            ["canon.skill.seuil-souille"] = new(4, "Single", true),
            ["canon.skill.service-du-the"] = new(3, "Single", true),
            ["canon.skill.tasse-retournee"] = new(4, "Single", true),
            ["canon.skill.etiquette"] = new(3, "Diamond", true),
            ["canon.skill.formule-creuse"] = new(4, "Single", true),
            ["canon.skill.courbette-inversee"] = new(0, "Single", false),
            ["canon.skill.chute-de-marbre"] = new(4, "Single", true),
            ["canon.skill.socle"] = new(0, "Single", false),
            ["canon.skill.verdict-du-seuil"] = new(4, "Single", true),
            ["canon.skill.dictee"] = new(4, "Single", true),
            ["canon.skill.plume-seche"] = new(4, "Single", true),
            ["canon.skill.encre-vive"] = new(4, "Single", true),
            ["canon.skill.recharge"] = new(3, "Single", true),
            ["canon.skill.eclaboussure"] = new(3, "Diamond", true),
            ["canon.skill.corps-de-verre"] = new(0, "Single", false),
            ["canon.skill.phrase-inachevee"] = new(4, "Single", true),
            ["canon.skill.marge-blanche"] = new(4, "Single", true),
            ["canon.skill.repli-de-papier"] = new(0, "Single", false),
            ["canon.skill.couture"] = new(1, "Single", false),
            ["canon.skill.reliure-de-chair"] = new(4, "Single", true),
            ["canon.skill.noeud-final"] = new(4, "Single", true),
            ["canon.skill.griffe-dos"] = new(1, "Single", false),
            ["canon.skill.fragment-grave"] = new(4, "Single", true),
            ["canon.skill.etreinte-creuse"] = new(1, "Single", false),
            ["canon.skill.effondrement"] = new(3, "Diamond", true),
            ["canon.skill.braise-memorielle"] = new(0, "Single", false),
            ["canon.skill.jet-de-cendre"] = new(4, "Single", true),
            ["canon.skill.fardeau-partage"] = new(3, "Single", true),
            ["canon.skill.berceuse-inversee"] = new(3, "Diamond", true),
            ["canon.skill.note-tenue"] = new(4, "Single", true),
            ["canon.skill.morsure-composite"] = new(1, "Single", false),
            ["canon.skill.bond-de-flanc"] = new(1, "Single", false),
            ["canon.skill.curee"] = new(1, "Single", false),
            ["canon.skill.guet"] = new(0, "Single", false),
            ["canon.skill.designation"] = new(4, "Single", true),
            ["canon.skill.houlette"] = new(4, "Single", true),
            ["canon.skill.ration"] = new(3, "Diamond", true),
            ["canon.skill.brout"] = new(0, "Single", false),
            ["canon.skill.regard-fixe"] = new(4, "Single", true),
            ["canon.skill.belement-a-lenvers"] = new(4, "Single", true),
            ["canon.skill.detente"] = new(3, "Diamond", true),
            ["canon.skill.coup-de-plaque"] = new(1, "Single", false),
            ["canon.skill.foyer-ouvert"] = new(4, "Single", true),
            ["canon.skill.redressement"] = new(0, "Single", false),
            ["canon.skill.frappe-denclume"] = new(1, "Cross", false),
            ["canon.skill.cadence"] = new(0, "Single", false),
            ["canon.skill.coup-de-grace-forgeron"] = new(1, "Single", false),
            ["canon.skill.transmutation-alliee"] = new(3, "Single", true),
            ["canon.skill.litanie"] = new(3, "Diamond", true),
            ["canon.skill.scorie"] = new(4, "Single", true),
            ["canon.skill.fonte"] = new(0, "Single", false),
            ["canon.skill.contact"] = new(1, "Single", false),
            ["canon.skill.laitier-ardent"] = new(4, "Single", true),
            ["canon.skill.eclat-vitrifie"] = new(4, "Single", true),
            ["canon.skill.reformation"] = new(0, "Single", false),
            ["canon.skill.placebo"] = new(0, "Single", false),
            ["canon.skill.bordage"] = new(4, "Single", true),
            ["canon.skill.injection-blanche"] = new(3, "Single", true),
            ["canon.skill.drap-tendu"] = new(4, "Single", true),
            ["canon.skill.sonnette"] = new(0, "Single", false),
            ["canon.skill.visite"] = new(4, "Single", true),
            ["canon.skill.tour-de-clef"] = new(4, "Single", true),
            ["canon.skill.trousseau"] = new(4, "Single", true),
            ["canon.skill.extinction-des-feux"] = new(4, "Single", true),
            ["canon.skill.baton-de-marche"] = new(1, "Single", false),
            ["canon.skill.chapelet-de-dents"] = new(4, "Single", true),
            ["canon.skill.repentir"] = new(0, "Single", false),
            ["canon.skill.encens-inverse"] = new(3, "Diamond", true),
            ["canon.skill.oraison-cousue"] = new(4, "Single", true),
            ["canon.skill.derniere-priere"] = new(4, "Single", true),
            ["canon.skill.posture-finale"] = new(4, "Single", true),
            ["canon.skill.griffe-de-recul"] = new(1, "Single", false),
            ["canon.skill.salut-de-chapeau"] = new(1, "Single", false),
            ["canon.skill.conversation-tranquille"] = new(4, "Single", true),
            ["canon.skill.pas-de-promenade"] = new(0, "Single", false),
            ["canon.skill.sifflotement"] = new(3, "Diamond", true),
            ["canon.skill.secateur"] = new(1, "Single", false),
            ["canon.skill.emondage"] = new(1, "Single", false),
            ["canon.skill.greffe"] = new(3, "Single", true),
            ["canon.skill.paillage"] = new(3, "Single", true),
            ["canon.skill.poing-de-crystal"] = new(1, "Single", false),
            ["canon.skill.refraction"] = new(4, "Single", true),
            ["canon.skill.stase"] = new(4, "Single", true),
            ["canon.skill.facette"] = new(0, "Single", false),
            ["canon.skill.pulsation"] = new(4, "Single", true),
            ["canon.skill.prisme"] = new(0, "Single", false),
            ["canon.skill.eclat-echo-colere"] = new(4, "Single", true),
            ["canon.skill.constat-sec"] = new(4, "Single", true),
            ["canon.skill.montee"] = new(0, "Single", false),
            ["canon.skill.explosion"] = new(3, "Diamond", true),
            ["canon.skill.frisson"] = new(4, "Single", true),
            ["canon.skill.porte-fermee"] = new(4, "Single", true),
            ["canon.skill.saccade"] = new(0, "Single", false),
            ["canon.skill.poids"] = new(4, "Single", true),
            ["canon.skill.constat-tardif"] = new(4, "Single", true),
            ["canon.skill.silence-partage"] = new(int.MaxValue, "Map", false),
            ["canon.skill.maree-montante"] = new(3, "Diamond", true),
            ["canon.skill.lame-de-fond"] = new(1, "Single", false),
            ["canon.skill.lame-de-fond-renforcee"] = new(1, "Single", false),
        };

    public static CanonicalTacticalSkillContract Require(string skillKey) =>
        ByKey.TryGetValue(skillKey, out var contract)
            ? contract
            : throw new InvalidOperationException(
                $"Skill '{skillKey}' is missing its mandatory tactical contract.");
}
