// <auto-generated />
using System;
using Leds.GameEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Leds.GameEngine.Infrastructure.Migrations
{
    [DbContext(typeof(GameEngineDbContext))]
    partial class GameEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.ActiveCurseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<string>("CurseDefinitionKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("curse_definition_key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<double>("DifficultyDelta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("difficulty_delta");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("NextCombatOnly")
                        .HasColumnName("duration");

                    b.Property<string>("EffectSetKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("effect_set_key");

                    b.Property<Guid?>("ExpiresAtRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("expires_at_room_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<Guid?>("RunEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("Severity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("CurseDefinitionKey")
                        .HasDatabaseName("IX_run_active_curses_curse_definition_key");

                    b.HasIndex("RunEntityId");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_run_active_curses_run_id");

                    b.ToTable("run_active_curses", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.AdaptiveInfluenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("duration");

                    b.Property<string>("InfluenceTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("influence_tag");

                    b.Property<string>("InfluenceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("influence_type");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("value");

                    b.Property<string>("ValueMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("value_mode");

                    b.HasKey("Id");

                    b.HasIndex("InfluenceTag")
                        .HasDatabaseName("IX_run_adaptive_influences_influence_tag");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_run_adaptive_influences_run_id");

                    b.HasIndex("SourceType")
                        .HasDatabaseName("IX_run_adaptive_influences_source_type");

                    b.ToTable("run_adaptive_influences", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatActionRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorSide")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_side");

                    b.Property<Guid>("CombatId")
                        .HasColumnType("uuid")
                        .HasColumnName("combat_id");

                    b.Property<int>("DamageDealt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("damage_dealt");

                    b.Property<int>("DamageTaken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("damage_taken");

                    b.Property<string>("EffectsApplied")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("effects_applied");

                    b.Property<int>("GuardAbsorbed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("guard_absorbed");

                    b.Property<int>("GuardDamage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("guard_damage");

                    b.Property<int>("GuardGained")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("guard_gained");

                    b.Property<int>("HealingDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("healing_done");

                    b.Property<int>("HealingReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("healing_received");

                    b.Property<int>("MitigatedDamage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mitigated_damage");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<int>("RawDamage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("raw_damage");

                    b.Property<string>("SkillDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("skill_display_name");

                    b.Property<string>("SkillKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("skill_key");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourceType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_type");

                    b.Property<string>("TargetIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("target_ids");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.Property<int>("VitalityDamage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vitality_damage");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("CombatId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("TurnNumber");

                    b.ToTable("run_combat_actions", (string)null);
                });

            modelBuilder.Entity("Leds.GameEngine.Infrastructure.Persistence.Entities.CombatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveCombatantId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_combatant_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentTick")
                        .HasColumnType("integer")
                        .HasColumnName("current_tick");

                    b.Property<int>("DotDurationExtensionTicks")
                        .HasColumnType("integer")
                        .HasColumnName("dot_duration_extension_ticks");

                    b.Property<int>("DotMagnitudeBonus")
                        .HasColumnType("integer")
                        .HasColumnName("dot_magnitude_bonus");

                    b.Property<bool>("DuelDamageAsymmetryEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("duel_damage_asymmetry_enabled");

                    b.Property<bool>("FalaiseWindEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("falaise_wind_enabled");

                    b.Property<bool>("FirstHitCriticalEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("first_hit_critical_enabled");

                    b.Property<string>("ForgottenSkillKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("forgotten_skill_key");

                    b.Property<bool>("HasFirstHitLanded")
                        .HasColumnType("boolean")
                        .HasColumnName("has_first_hit_landed");

                    b.Property<bool>("HasMirrorTriggered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_mirror_triggered");

                    b.Property<bool>("HealingBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("healing_blocked");

                    b.Property<int>("HitCounter")
                        .HasColumnType("integer")
                        .HasColumnName("hit_counter");

                    b.Property<bool>("HitCounterDoubleDamageEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("hit_counter_double_damage_enabled");

                    b.Property<bool>("LowHpDamageAmplificationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("low_hp_damage_amplification_enabled");

                    b.Property<bool>("MiroirEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("miroir_enabled");

          